Add required directories
Signed-off-by: Lukas Zapletal <lzap+git@redhat.com>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,10 +29,10 @@ jobs:
         run: |
           for DIR in guides/doc-*; do
             pushd $DIR &>/dev/null
+            [[ -d images/ ]] || (echo "Required images/ directory missing in $DIR"; exit 1)
+            [[ -h images/common ]] || (echo "Required images/common symlink missing in $DIR"; exit 1)
             if [[ -f docinfo.xml ]]; then
               echo "Running ccutil in $DIR"
-              [[ -d images/ ]] || mkdir images
-              cp -rl common/images/* images/
               sed -i "1 i:build: satellite\n" master.adoc
               ccutil compile --lang=en-US --format html-single
             else
